package com.wallet.utils;

import com.google.common.base.Strings;

import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.StringTokenizer;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static com.google.common.collect.Lists.newArrayList;
import static com.google.common.collect.Maps.newHashMap;
import static com.wallet.utils.ConsoleUtils.println;

/**
 * Created by EBR3556 on 09/11/2017.
 */
public class UtilTEst {


    public static void main(String[] args) {
        List<String> ssss = newArrayList();
        ssss.add(" REMBOURST CB DU 081017 AMAZON PAYMENTS P");
        ssss.add(" REMBOURST CB DU 160717 LEROY MERLIN VITR");
        ssss.add("CHEQUE 8635463");
        ssss.add("COMMISSIONS - ABONNEMENT FORFAIT 15 ALERTES SMS DU 0");
        ssss.add("COMMISSIONS COTISATION ESPRIT LIBRE");
        ssss.add("ECHEANCE PRET 02908 60255786 (CAPITAL DU 3024,90 EUR)");
        ssss.add("ECHEANCE PRET 02908 60255786 (CAPITAL DU 3210,63 EUR)");
        ssss.add("ECHEANCE PRET 02908 60255786 (CAPITAL DU 3395,98 EUR)");
        ssss.add("ECHEANCE PRET 02908 60255786 (CAPITAL DU 3580,94 EUR)");
        ssss.add("ECHEANCE PRET 02908 60255786 (CAPITAL DU 3765,52 EUR)");
        ssss.add("FACTURE CARTE DU 010717 H&M011 PARIS CARTE 4974XXXXXXX");
        ssss.add("FACTURE CARTE DU 010917 LES DEUX FRERES PARIS CARTE 49");
        ssss.add("FACTURE CARTE DU 011017 BARGE CROUS PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 011117 SELECTA METROC0 AUBERVILLIERS");
        ssss.add("FACTURE CARTE DU 020717 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 020717 UBER BV CARTE 4974XXXXXXXX2310");
        ssss.add("FACTURE CARTE DU 020817 ANCIEN RES CHAR PARIS 9 CARTE");
        ssss.add("FACTURE CARTE DU 020817 GO SPORT FRANCE BOULOGNE BILL");
        ssss.add("FACTURE CARTE DU 020917 CANDELLA III PARIS CARTE 4974X");
        ssss.add("FACTURE CARTE DU 030817 MULTISTORE SCHE ORLY AEROGARE");
        ssss.add("FACTURE CARTE DU 030917 GLADINES ST-GER PARIS 5 CARTE");
        ssss.add("FACTURE CARTE DU 031117 LE BAMBOU PARIS CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 031117 MK2 TOLBIAC PARIS TOLBIA/ CART");
        ssss.add("FACTURE CARTE DU 031117 UNIQLO OPERA 08 PARIS CARTE 49");
        ssss.add("FACTURE CARTE DU 040717 LE PATRIZIA BOULOGNE BILL CART");
        ssss.add("FACTURE CARTE DU 041017 GRANDE PHARMACI VITRY SUR SEI");
        ssss.add("FACTURE CARTE DU 051117 MAK CHICKEN IVRY SUR SEIN CART");
        ssss.add("FACTURE CARTE DU 060817 93002 AELIA DUT CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 060917 LA POSTE L92106 BOULOGNE BILL");
        ssss.add("FACTURE CARTE DU 061017 LES DEUX FRERES PARIS CARTE 49");
        ssss.add("FACTURE CARTE DU 061017 O NEIL PARIS CARTE 4974XXXXXXX");
        ssss.add("FACTURE CARTE DU 070717 FRANPRIX NANO SAINT DENIS CART");
        ssss.add("FACTURE CARTE DU 070717 SC-SMILE & PAY PARIS CARTE 497");
        ssss.add("FACTURE CARTE DU 070817 FRANPRIX PARIS 05 CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 071017 BIG FERNAND PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 080817 AMAZON EU SARL PARIS2090401/ C");
        ssss.add("FACTURE CARTE DU 080817 AMAZON PAYMENTS PARIS2441535/");
        ssss.add("FACTURE CARTE DU 080917 LEVY AHA GP PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 080917 UBER PARIS CARTE 4974XXXXXXXX2");
        ssss.add("FACTURE CARTE DU 081017 AMAZON PAYMENTS PARIS2441535/");
        ssss.add("FACTURE CARTE DU 081017 AMAZON PAYMENTS PARIS2441535/");
        ssss.add("FACTURE CARTE DU 081017 AMAZON PAYMENTS PARIS2441535/");
        ssss.add("FACTURE CARTE DU 090717 LEROY MERLIN VITRY SUR SEI CAR");
        ssss.add("FACTURE CARTE DU 090717 O TASTY IVRY SUR SEIN CARTE 49");
        ssss.add("FACTURE CARTE DU 090917 LES SANS CULOTT PARIS 11 CARTE");
        ssss.add("FACTURE CARTE DU 090917 SUMUP *EQUINOX CARTE 4974XXXXX");
        ssss.add("FACTURE CARTE DU 091017 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 110717 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 110817 CHAROLAIS PARIS CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 110817 CHAROLAIS PARIS CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 110817 CHAROLAIS PARIS CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 110917 LA POSTE L92042 BOULOGNE BILL");
        ssss.add("FACTURE CARTE DU 111017 TICKETNET NANTERRE CEDE CARTE");
        ssss.add("FACTURE CARTE DU 120817 REST DKL PARIS CARTE 4974XXXXX");
        ssss.add("FACTURE CARTE DU 121017 LE VOLTAIRE CHATENAY-MAL CARTE");
        ssss.add("FACTURE CARTE DU 121017 RATP PARIS CEDEX 1 CARTE 4974X");
        ssss.add("FACTURE CARTE DU 130717 BRTMKT DBA FAST CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 130717 DECATHLON PARIS CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 130717 FOYER MILIT CCL PARIS CARTE 49");
        ssss.add("FACTURE CARTE DU 130817 DELIVEROOFR CARTE 4974XXXXXXXX");
        ssss.add("FACTURE CARTE DU 140717 FOYER MILIT CCL PARIS CARTE 49");
        ssss.add("FACTURE CARTE DU 140817 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 140917 ESPACE VERT IVRY SUR SEI CARTE");
        ssss.add("FACTURE CARTE DU 141017 REST. LA LUGE PARIS CARTE 4974");
        ssss.add("FACTURE CARTE DU 150717 LEROY MERLIN SC VITRY SUR SEI");
        ssss.add("FACTURE CARTE DU 150817 UBER PARIS CARTE 4974XXXXXXXX2");
        ssss.add("FACTURE CARTE DU 150917 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 160717 LEROY MERLIN VITRY SUR SEI CAR");
        ssss.add("FACTURE CARTE DU 170717 AMAZON PAYMENTS PARIS2441535/");
        ssss.add("FACTURE CARTE DU 170717 AMAZON.FR/PREM PARIS2469664/ C");
        ssss.add("FACTURE CARTE DU 170917 UBER PARIS CARTE 4974XXXXXXXX2");
        ssss.add("FACTURE CARTE DU 180617 UBER PARIS CARTE 4974XXXXXXXX9");
        ssss.add("FACTURE CARTE DU 180917 LC FITNESS VITR GOUVERNES CART");
        ssss.add("FACTURE CARTE DU 190817 LEROY MERLIN SC VITRY SUR SEI");
        ssss.add("FACTURE CARTE DU 190917 FOODCHERICOM CARTE 4974XXXXXXX");
        ssss.add("FACTURE CARTE DU 191017 COEUR DE CREPES MORANGIS CARTE");
        ssss.add("FACTURE CARTE DU 200717 CASINO PARIS CARTE 4974XXXXXXX");
        ssss.add("FACTURE CARTE DU 200817 LA FABBRICA DE ST GERMAIN E CA");
        ssss.add("FACTURE CARTE DU 200817 LAFFITTE EPICER MAISONS LAFFI");
        ssss.add("FACTURE CARTE DU 200817 SNCF PARIS 8 CARTE 4974XXXXXXX");
        ssss.add("FACTURE CARTE DU 200917 MONOPRIX ISSY LES MOUL CARTE 4");
        ssss.add("FACTURE CARTE DU 200917 MONOPRIX ISSY LES MOUL CARTE 4");
        ssss.add("FACTURE CARTE DU 201017 GEANT CG327 PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 210717 MI PERU PARIS CARTE 4974XXXXXX");
        ssss.add("FACTURE CARTE DU 210817 BRICOLEX BOULOGNE BILL CARTE 4");
        ssss.add("FACTURE CARTE DU 210817 LA POSTE L92042 BOULOGNE BILL");
        ssss.add("FACTURE CARTE DU 211017 CARREFOUR CRETE CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 211017 LES PIAULES PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 211017 LES PIAULES PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 211017 PRIMARK CRETEIL CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 220717 CARREFOURMARKET CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 221017 BARGE CROUS PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 230617 H&M007 PARIS CARTE 4974XXXXXXX");
        ssss.add("FACTURE CARTE DU 230617 UNIQLO OPERA 04 PARIS CARTE 49");
        ssss.add("FACTURE CARTE DU 230817 NATURALIA CLICHY CARTE 4974XXX");
        ssss.add("FACTURE CARTE DU 240617 SPOTIFY FRANCE PARIS CARTE 497");
        ssss.add("FACTURE CARTE DU 240717 SPOTIFY P02F9F6 CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 240817 SPOTIFY P033B5D CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 241017 SPOTIFY FRANCE PARIS CARTE 497");
        ssss.add("FACTURE CARTE DU 241017 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 250717 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 250817 ISTANBUL IVRY SUR SEIN CARTE 4");
        ssss.add("FACTURE CARTE DU 250817 PRIMARK CRETEIL CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 260717 LA POSTE L92042 BOULOGNE BILL");
        ssss.add("FACTURE CARTE DU 260817 LA CANTINE PHIL PARIS CARTE 49");
        ssss.add("FACTURE CARTE DU 260817 LES PIAULES PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 261017 NEW PERLE D ASI CHATENAY MAL C");
        ssss.add("FACTURE CARTE DU 270617 AMAZON PAYMENTS PARIS2441535/");
        ssss.add("FACTURE CARTE DU 270817 AMAZON EU SARL PARIS2090401/ C");
        ssss.add("FACTURE CARTE DU 270817 O TACOS PARIS CARTE 4974XXXXXX");
        ssss.add("FACTURE CARTE DU 271017 CARREFCITYSCO CARTE 4974XXXXXX");
        ssss.add("FACTURE CARTE DU 271017 LES DEUX FRERES PARIS CARTE 49");
        ssss.add("FACTURE CARTE DU 280917 PRIMARK CRETEIL CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 290617 GO SPORT FRANCE BOULOGNE BILL");
        ssss.add("FACTURE CARTE DU 290717 REST DKL PARIS CARTE 4974XXXXX");
        ssss.add("FACTURE CARTE DU 290917 LA GROSSE CAISS PARIS 02 CARTE");
        ssss.add("FACTURE CARTE DU 291017 MUKURA PARIS CARTE 4974XXXXXXX");
        ssss.add("FACTURE CARTE DU 300717 SELECTA METROC0 AUBERVILLIERS");
        ssss.add("FACTURE CARTE DU 300717 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 300817 MME SHAWN BAT PARIS CARTE 4974");
        ssss.add("FACTURE CARTE DU 300917 GEANT CG327 PARIS CARTE 4974XX");
        ssss.add("FACTURE CARTE DU 300917 SC-ALIM-SEGMAT PARIS CARTE 497");
        ssss.add("FACTURE CARTE DU 310717 LC FITNESS VITR GOUVERNES CART");
        ssss.add("FACTURE CARTE DU 310817 SUPERMARCHE G20 IVRY SUR SEIN");
        ssss.add("FACTURE CARTE DU 311017 BOULINIER PARIS CARTE 4974XXXX");
        ssss.add("FACTURE CARTE DU 311017 WESTERN UNION COURBEVOIE CARTE");
        ssss.add("PRLV SEPA 7A77 FITNESS ECH/050717 ID EMETTEUR/FR11");
        ssss.add("PRLV SEPA 7A77 FITNESS ECH/050917 ID EMETTEUR/FR11");
        ssss.add("PRLV SEPA 7A77 FITNESS ECH/051017 ID EMETTEUR/FR11");
        ssss.add("PRLV SEPA 7A77 FITNESS ECH/061117 ID EMETTEUR/FR11");
        ssss.add("PRLV SEPA 7A77 FITNESS ECH/070817 ID EMETTEUR/FR11");
        ssss.add("PRLV SEPA A.F IMMOBILIER A.F IMMOBILIER ECH/050717");
        ssss.add("PRLV SEPA A.F IMMOBILIER A.F IMMOBILIER ECH/050917");
        ssss.add("PRLV SEPA A.F IMMOBILIER A.F IMMOBILIER ECH/051017");
        ssss.add("PRLV SEPA A.F IMMOBILIER A.F IMMOBILIER ECH/061117");
        ssss.add("PRLV SEPA A.F IMMOBILIER A.F IMMOBILIER ECH/070817");
        ssss.add("PRLV SEPA AVANSSUR ECH/040717 ID EMETTEUR/FR64ZZZ3");
        ssss.add("PRLV SEPA AVANSSUR ECH/040817 ID EMETTEUR/FR64ZZZ3");
        ssss.add("PRLV SEPA AVANSSUR ECH/040917 ID EMETTEUR/FR64ZZZ3");
        ssss.add("PRLV SEPA AVANSSUR ECH/041017 ID EMETTEUR/FR64ZZZ3");
        ssss.add("PRLV SEPA AVANSSUR ECH/041017 ID EMETTEUR/FR64ZZZ3");
        ssss.add("PRLV SEPA AVANSSUR ECH/061117 ID EMETTEUR/FR64ZZZ3");
        ssss.add("PRLV SEPA BOUYGUES TELECOM ECH/200617 ID EMETTEUR/");
        ssss.add("PRLV SEPA BOUYGUES TELECOM ECH/200717 ID EMETTEUR/");
        ssss.add("PRLV SEPA BOUYGUES TELECOM ECH/200917 ID EMETTEUR/");
        ssss.add("PRLV SEPA BOUYGUES TELECOM ECH/201017 ID EMETTEUR/");
        ssss.add("PRLV SEPA BOUYGUES TELECOM ECH/210817 ID EMETTEUR/");
        ssss.add("PRLV SEPA CARDIF - ASSURANCES RISQUES DIVERS ECH/1");
        ssss.add("PRLV SEPA CARDIF ASSURANCE VIE ECH/050717 ID EMETT");
        ssss.add("PRLV SEPA CARDIF ASSURANCE VIE ECH/050917 ID EMETT");
        ssss.add("PRLV SEPA CARDIF ASSURANCE VIE ECH/051017 ID EMETT");
        ssss.add("PRLV SEPA CARDIF ASSURANCE VIE ECH/061117 ID EMETT");
        ssss.add("PRLV SEPA CARDIF ASSURANCE VIE ECH/070817 ID EMETT");
        ssss.add("PRLV SEPA FITNESS PARK VITRY-LC FITNESS VITRY ECH/");
        ssss.add("PRLV SEPA FITNESS PARK VITRY-LC FITNESS VITRY ECH/");
        ssss.add("PRLV SEPA NAVIGO ANNUEL - GIE COMUTITRES ECH/03071");
        ssss.add("PRLV SEPA NAVIGO ANNUEL - GIE COMUTITRES ECH/03081");
        ssss.add("PRLV SEPA NAVIGO ANNUEL - GIE COMUTITRES ECH/03101");
        ssss.add("PRLV SEPA NAVIGO ANNUEL - GIE COMUTITRES ECH/03111");
        ssss.add("PRLV SEPA NAVIGO ANNUEL - GIE COMUTITRES ECH/04091");
        ssss.add("PRLV SEPA ORANGE ECH/091017 ID EMETTEUR/FR18ZZZ002");
        ssss.add("PRLV SEPA ORANGE ECH/100717 ID EMETTEUR/FR18ZZZ002");
        ssss.add("PRLV SEPA ORANGE ECH/100817 ID EMETTEUR/FR18ZZZ002");
        ssss.add("PRLV SEPA ORANGE ECH/110917 ID EMETTEUR/FR18ZZZ002");
        ssss.add("RETRAIT DAB 08/07/17 10H42 146880 BNP PARIBAS PARIS");
        ssss.add("RETRAIT DAB 12/10/17 22H03 154060 BNP PARIBAS PARIS");
        ssss.add("RETRAIT DAB 14/09/17 14H05 290890 BNP PARIBAS BOULOG");
        ssss.add("RETRAIT DAB 19/08/17 17H06 089510 BNP PARIBAS PARIS");
        ssss.add("RETRAIT DAB 20/07/17 23H47 00017211 BRED PARIS METIV");
        ssss.add("RETRAIT DAB 23/06/17 13H43 290839 BNP PARIBAS BOULOG");
        ssss.add("RETRAIT DAB 23/07/17 17H25 293301 BNP PARIBAS PARIS");
        ssss.add("RETRAIT DAB 25/06/17 22H19 07993925 CRCA ILE DE FRAN");
        ssss.add("RETRAIT DAB 31/07/17 17H39 290890 BNP PARIBAS BOULOG");
        ssss.add("VIR CPTE A CPTE EMIS /MOTIF EPARGNE /BEN BRAVO SANCHEZ JO /RE");
        ssss.add("VIR CPTE A CPTE EMIS /MOTIF EPARGNE /BEN BRAVO SANCHEZ JO /RE");
        ssss.add("VIR CPTE A CPTE EMIS /MOTIF EPARGNE /BEN BRAVO SANCHEZ JO /RE");
        ssss.add("VIR CPTE A CPTE RECU /DE BRAVO SANCHEZ JO /MOTIF EPARGNE /REF");
        ssss.add("VIR CPTE A CPTE RECU /DE BRAVO SANCHEZ JO /MOTIF EPARGNE /REF");
        ssss.add("VIR SEPA RECU /DE BETANCO /MOTIF INTERNET-FAVEUR ESTEB");
        ssss.add("VIR SEPA RECU /DE MANGOPAY SA /MOTIF PUMPKIN BY MANGOP");
        ssss.add("VIR SEPA RECU /DE SFR /MOTIF REMBOURSEMENT SFR MOBILE");
        ssss.add("VIR SEPA RECU /DE SUAREZ MORENO KA /MOTIF PRAGA /REF");
        ssss.add("VIR SEPA RECU /DE SUAREZ MORENO KA /MOTIF SAC COUCHAGE");
        ssss.add("VIR SEPA RECU /DE VISEO TECHNOLOGIES /MOTIF /REF 2017-");
        ssss.add("VIR SEPA RECU /DE VISEO TECHNOLOGIES /MOTIF /REF 2017-");
        ssss.add("VIR SEPA RECU /DE VISEO TECHNOLOGIES /MOTIF /REF 2017-");
        ssss.add("VIR SEPA RECU /DE VISEO TECHNOLOGIES /MOTIF /REF 2017-");
        ssss.add("VIR SEPA RECU /DE VISEO TECHNOLOGIES /MOTIF VIREMENT 2");
        ssss.add("VIREMENT SEPA EMIS /MOTIF ATERCIOPELADOS /BEN LUISA F MURCI");
        ssss.add("VIREMENT SEPA EMIS /MOTIF DE TODO UN POCO /BEN CORTES MAHEC");
        ssss.add("VIREMENT SEPA EMIS /MOTIF ENERG A JULIO /BEN JUAN DAVID BET");
        ssss.add("VIREMENT SEPA EMIS /MOTIF ITALIE ET PRAGUE /BEN SANDOVAL RI");
        ssss.add("VIREMENT SEPA EMIS /MOTIF LUZ /BEN JUAN DAVID BETANCOURT /R");
        ssss.add("VRST ESPECES AUTOMATE 10/10/17 12H38 0160438");

        Long init = System.nanoTime();
        System.out.println("-----------------------------------------------------------");

        Map<String, List<String>> tokenToStringMap = newHashMap();

        ssss.stream()
                .map(s -> {
                    return Stream.of(s.split("\\s+"))
                            .limit(5)
                            .reduce((s1, s2) -> s1 + " " + s2)
                            .map(ss -> ss.replaceAll("ECH\\/[0-3][0-9][0-1][0-9][0-9][0-9]", "ECH\\@@@@@@"))
                            .orElse("");
                })
                .distinct()
                .forEach(s -> tokenToStringMap.putIfAbsent(s, newArrayList()));

        tokenToStringMap
                .forEach((pattern, strings) -> {
                    strings.addAll(ssss.stream()
                            .filter(s -> s
                                    .replaceAll("ECH\\/[0-3][0-9][0-1][0-9][0-9][0-9]", "ECH\\@@@@@@")
                                    .trim().regionMatches(true, 0, pattern.trim(), 0, pattern.trim().length()))
                            .collect(Collectors.toList()));
                });

//        Long end = System.nanoTime();

        final long duration = System.nanoTime() - init;
        final double seconds = ((double) duration / 1000000000);
        System.out.println("-----------------------------------------------------------------");
        System.out.println("solution Time : " + new DecimalFormat("#.##########").format(seconds) + " Seconds");
        System.out.println("-----------------------------------------------------------------");


        tokenToStringMap
                .forEach((pattern, strings) -> {
                    if (strings.size() > 1) {
                        println("pattern: " + pattern, ConsoleUtils.ANSI_GREEN);
                        strings.forEach(System.out::println);
                    }

                });


    }
}
